### ISSUE TITLE
Proper remove API for associations

### ISSUE THREAD

**Issue by mde** [geddy/model#136]
Right now it's possible to remove associations manually, but that's horrible and janky. We need a real API. The auto-removal of owned associated items when removing the owner might be a different issue, but we need that too.

**Comment by jorr** [comment]
> The auto-removal of owned associated items when removing the owner might be a different issue, but we need that too.

Is this actually live in Geddy as of now? Do I need to care about orphan owned items in the DB, maybe remove them on beforeRemove, or some such?
