### ISSUE TITLE
Migrations with autoIncrementId = true failing in Mysql

### ISSUE THREAD

**Issue by der-On** [geddy/model#237]
This is due to the SQL generator beeing optimized for Postgres and not for mysql: https://github.com/geddy/model/blob/master/lib/generators/sql.js#L88

Changing "BIGSERAIAL" in that line to "BIGINT(20) auto_increment" fixes the problem, but would propably introduce a problem in postgres. I'm not sure how to distinguish between mysql/postgres here.

**Comment by AlexRaylight** [comment]
The latest version on NPM is still 6.0.1, which has the broken mysql autoincrement, and propagates the issue to geddy...
